// File generated by FlutterFire CLI.
// THIS IS A TEMPORARY FILE - PLEASE RUN `flutterfire configure` TO GENERATE THE REAL ONE
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5muQ7UKV7r4mHUBRa4AYGynGQ46wTVk',
    appId: '1:1081896455408:web:80381629ece7eb15088635',
    messagingSenderId: '1081896455408',
    projectId: 'foodsaver-app-255ac',
    authDomain: 'foodsaver-app-255ac.firebaseapp.com',
    storageBucket: 'foodsaver-app-255ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1o_sfQ-_Lbziso1ZbXRhxmwP5275_MOg',
    appId: '1:1081896455408:android:c66b1a768413eb6a088635',
    messagingSenderId: '1081896455408',
    projectId: 'foodsaver-app-255ac',
    storageBucket: 'foodsaver-app-255ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5V91HVQcsobEnXh6x8KE-lq8DNhF5dI',
    appId: '1:1081896455408:ios:c206147ee338f281088635',
    messagingSenderId: '1081896455408',
    projectId: 'foodsaver-app-255ac',
    storageBucket: 'foodsaver-app-255ac.firebasestorage.app',
    iosBundleId: 'com.ralfiz.foodsaverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5V91HVQcsobEnXh6x8KE-lq8DNhF5dI',
    appId: '1:1081896455408:ios:c206147ee338f281088635',
    messagingSenderId: '1081896455408',
    projectId: 'foodsaver-app-255ac',
    storageBucket: 'foodsaver-app-255ac.firebasestorage.app',
    iosBundleId: 'com.ralfiz.foodsaverApp',
  );

}